### ISSUE TITLE
Optional prefix for saved response filenames

### ISSUE THREAD

**Issue by gffhcks** [garnaat/placebo#20]
I noticed that each time Placebo writes a new response JSON file, it adds a `_<number>` suffix before the `.json`, and simply increments the suffix until it finds one that doesn't exist yet. This is better than overwriting previous runs, but doesn't give any way to distinguish multiple runs.

What would be really nice, is if you could optionally set a `prefix` argument on a `Pill` object. This prefix would be applied to all filenames written by the pill, like so: `prefix.iam.ListUserPolicies_1.json`.

I can think of two good use cases for this:

1. Define the prefix uniquely on each execution, using a command line argument, timestamp, or some other generated value. Now individual executions can be reloaded and replayed, or even diffed for comparison.
2. For an application that uses multiple Boto sessions, define a different prefix for each session. For example, I can use `base` for my initial credentials session, `mfa` for my new session after MFA authentication, and `<rolename>` for a session created using an IAM role.  I can even combine that with a timestamp (as in case 1) to separate multiple runs.

**Comment by garnaat** [comment]
Good idea.  And should be pretty easy to implement.

**Comment by gffhcks** [comment]
I have some code for it that I've played around with that should work, but haven't written tests and probably won't get a chance to today. Should I submit a PR with what I have, or do you want to just run with it?

**Comment by garnaat** [comment]
Go ahead an do a PR.  If I have time, I can try to add some tests or you can add them when you get a chance.

**Comment by gffhcks** [comment]
Finally got around to adding two simple unit tests. @garnaat let me know you think anything else should be tested.
