### ISSUE TITLE
Loading multiple stored responses in single test

### ISSUE THREAD

**Issue by avs3323** [garnaat/placebo#22]
Hi,

I have a unit test set up where I have recorded the results from a valid run, and an invalid run.

I have 2 recorded placebo files, one in each directory, structured like this ('./goodtest/xxx_1.json', './badtest/xxx_1.json')

I have 2 tests, where each test loads from a separate directory, like so:

    def test_verify_invalid(self):
        invalid_session = boto3.Session()
        pill = placebo.attach(invalid_session, data_path='./badtest/')
        pill.playback()

        with Replacer() as r:
            r.replace('src.SESSION', invalid_session)
            self.assertFalse(verify_thing(BADARGS))
            pill.stop()

    def test_verify_valid(self):
        valid_session = boto3.Session()
        pill = placebo.attach(valid_session, data_path='./goodtest/')
        pill.playback()

        with Replacer() as r:
            r.replace('src.SESSION', valid_session)
            self.assertTrue(verify_thing(GOODARGS))
            pill.stop()

However, I get the 'bad' event for both tests.  I have verified that if I take the 'good' output, and put it into the badtest folder (the one that is loaded first)  and name it 'xxx_2.json' , it works fine.

Am I doing something wrong?  I could have them both in the same folder, but that would require specific ordering of my tests, which doesn't seem right to me.

Thanks!

**Comment by garnaat** [comment]
That should not be happening.  I'm going to try to reproduce it.  Thanks.

**Comment by avs3323** [comment]
You can close this, I figured out what I was doing wrong.

In my actual code, I was caching the clients created by a session.  However, I was only using the replacer on the session itself.  So each test case was pulling the cached 'placeboed' client from the first test.
