### ISSUE TITLE
Requesting a release with 'prefix' argument included

### ISSUE THREAD

**Issue by ghicks-rmn** [garnaat/placebo#27]
I submitted a pull request a while back to add an optional 'prefix' argument, which I needed for tracking multiple sessions with Placebo. It's been merged into the project. but the latest '0.4.3' release does not have the argument.

Can we get a release pushed to PyPI that has the argument included? I already have code written that is depending on it, but I'm stuck importing my local development version until the feature is available in the public release.

**Comment by gffhcks** [comment]
Whoops, posted from the wrong account. That's me up there.

**Comment by benkehoe** [comment]
You can pip install direct from GitHub in the meantime: https://pip.pypa.io/en/stable/reference/pip_install/#git

**Comment by garnaat** [comment]
Sorry about that.  I somehow lost track of that.  I just released ``0.5.0`` which includes your PR.  Thanks for the ping!
