### ISSUE TITLE
Table really created in Dynamodb

### ISSUE THREAD

**Issue by beeva-ivanblanquez** [garnaat/placebo#46]
Hi Garnaat,

I'm trying to configure placebo to test my code, but I think I'm doing something bad. I not be able to configure placebo to work in local enviroment, I must use real credentials and when I use placebo to create a data base, It be created in AWS DynamoDB in my real account, if I use a not real credentials I get a conecttion error "ClientError: An error occurred (UnrecognizedClientException) when calling the CreateTable operation: The security token included in the request is invali"d  This is my code, Could you help me please?

```
import unittest

import boto3
import placebo
from placebo.utils import placebo_session


class TestIntegrationDynamodbTableDao(unittest.TestCase):
    __access_key = "Fake"
    __secret_key = "Fake"
    __token = "Fake"
    __region = "local"
    __table = None
    __resource = None
    __pill = None

    def setUp(self):
        pass

    def tearDown(self):
        self.__pill.stop()

    def test_given_when_then(self):
        # self.__session = boto3.Session(aws_access_key_id=self.__access_key, aws_secret_access_key=self.__secret_key, aws_session_token=self.__token,
        self.__session = boto3.Session(aws_access_key_id=self.__access_key, aws_secret_access_key=self.__secret_key, region_name=self.__region)
        self.__pill = placebo.attach(self.__session, data_path='/home/ivan/tmp')
        # self.__pill.record(services='dynamodb')
        # self.__pill.record()
        self.__resource = self.__session.resource('dynamodb')
        self.__pill.playback()
        self.__resource.create_table(TableName='test',
                                     KeySchema=[{'AttributeName': 'zn', 'KeyType': 'HASH'},
                                                {'AttributeName': 'dt', 'KeyType': 'RANGE'}],
                                     AttributeDefinitions=[{'AttributeName': 'zn', 'AttributeType': 'S'},
                                                           {'AttributeName': 'dt', 'AttributeType': 'S'}],
                                     ProvisionedThroughput={'ReadCapacityUnits': 5, 'WriteCapacityUnits': 5})
        self.__pill.stop()
        print "hello"


if __name__ == '__main__':
    unittest.main()
```

**Comment by fxfitz** [comment]
Ivan,

So the first time you run this, with real keys in record mode, it works and does actual things in AWS.

You're saying that the second time, when you use fake keys in **playback** mode, it yells at you?

Fran

**Comment by fxfitz** [comment]
You should only have to use real credentials when you're recording; when you playback with fake credentials, it should work.

**Comment by beeva-ivanblanquez** [comment]
Hi Fran,
I think I don't understand placebo behavior. So First time I must use real credentials and write truly in DynamoDB and after I can use plaback anywhere of code? If This is the case I think placebo is not the way to use as a "Mock" tool, becuase I need to have a real account in AWS.

Regards

**Comment by fxfitz** [comment]
Placebo is definitely valuable if you have an account and want to make run deterministic, repeatable tests without touching AWS (at least most of the time).  For example, in a project I'm working right now, I have a test suite which will spin up fresh EC2 instances and run tests on them, and then when the test is done it will terminate the instances.  Placebo records the EC2 interactions on the first go around (record mode), and then any time after that, when the tests are run, the recorded EC2 interactions are played back instead of using AWS (playback mode).

Doing it this way allows me to record the tests with valid credentials, redact the credentials (substituting with fake ones), and then check in all of my source code including the cassettes.  Since everything is now redacted, all of my tests will pass (tox and Travis CI) without valid credentials _even_ when I don't have an internet connection. The thing is, I need to have the recording first.

Here's some sample code from my recent project which allows me to rerecord and playback quite easily (I'm using pytest and pytest-variables):
```python
def get_aws_info(input_dict):
    return (input_dict.get('AWS_ACCESS_KEY', 'fake_access_key'),
            input_dict.get('AWS_SECRET_KEY', 'fake_secret_key'),
            input_dict.get('AWS_REGION_NAME', 'us-west-2'))


@pytest.fixture()
def boto3_session_mock(variables):
    aws = get_aws_info(variables)
    session = boto3.Session(aws_access_key_id=aws[0],
                            aws_secret_access_key=aws[1],
                            region_name=aws[2])

    pill = placebo.attach(session, data_path='tests/fixtures/aws_recordings')

    pill.record() if variables.get('RECORD_BOTO', False) else pill.playback()

    return session
```

I also have a tox environment to help me rerecord easily:
```
[testenv:rerecord]
deps = -r{toxinidir}/test-requirements.txt
whitelist_externals = /bin/bash
commands =
    /bin/bash -c 'rm -f {toxinidir}/tests/fixtures/aws_recordings/*.json'
    coverage run -m pytest {posargs} --variables placebo_record.json tests/test_awsrun_connection.py
```

If it helps, [vcrpy](https://github.com/kevin1024/vcrpy) is another popular record/playback library used for HTTP requests.  I used that library before placebo, and it definitely helped me understand the concepts.

**Comment by beeva-ivanblanquez** [comment]
Hi Fran,

Thanks for all your explanation. I became programming in Python a few weeks ago, and I don't understand very well testing phylosopy and tools. Your helps has been very helpful for me to use this librarty and others  record/playback libraries.

Thanks so much,

Best regards

**Comment by fxfitz** [comment]
:+1: let me know if you need anything

**Comment by alexharv074** [comment]
I'm rather struggling with this too.

I've tried this:

```
$ export AWS_ACCESS_KEY_ID=fake_access_key_id
$ export AWS_SECRET_ACCESS_KEY=fake_secret_access_key
```

That leads to my script failing with:

```
Traceback (most recent call last):
  File "scripts/aws_ec2_copy_image.py", line 210, in <module>
    main()
  File "scripts/aws_ec2_copy_image.py", line 193, in main
    if get_account_id() == get_ec2_image_account_id(vars(args)['source_ami_id']):
  File "scripts/aws_ec2_copy_image.py", line 76, in get_ec2_image_account_id
    response = client.describe_images(DryRun=False, ImageIds=[ami_id])
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 543, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AuthFailure) when calling the DescribeImages operation: AWS was not able to validate the provided access credentials
```

I note that this [example](https://github.com/gffhcks/placebo-example) implied a need for real access keys - but as noted above, it's no use to have a Mock framework that requires a connection to a real account.

README at this project isn't helping much.

@beeva-ivanblanquez , did you ever get this to work?

**Comment by alexharv074** [comment]
Here's my set up code:

~~~ python
  boto3.setup_default_session(
      aws_access_key_id='key',
      aws_secret_access_key='secret',
      aws_session_token='fake')
  session = boto3.DEFAULT_SESSION
  pill = placebo.attach(session, data_path='pyunit/fixtures')
  pill.playback()
~~~

**Comment by alexharv074** [comment]
Ok, ignore this. I had inadvertently recorded an `aws ec2 describe-images` response with Placebo that had returned an auth failure. All I need in my set up code is:

~~~ python
  boto3.setup_default_session()
  session = boto3.DEFAULT_SESSION
  pill = placebo.attach(session, data_path='pyunit/fixtures')
  pill.playback()
~~~
