### ISSUE TITLE
release new version to include #50 and #51

### ISSUE THREAD

**Issue by kapilt** [garnaat/placebo#63]
there's a couple of important fixes between the two (#50 and #51), but without a release its unclear if most users will find them except the hard way, and then have to update deps to use git checkouts :-( Much nicer would be releasing 0.8.2 to pypi

**Comment by garnaat** [comment]
I'm planning on doing a release on Monday, if not before.  Let me know if there are any other changes you would like to see in that next release.

**Comment by garnaat** [comment]
New 0.8.2 is out (https://pypi.org/project/placebo/).  It's been a while since I've done this release process so let me know if you notice any issues.

I'd like to start working on a 0.9.0 release now.
